/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { FundControllerContract } from "./FundController";
import { FundDelegatorContract } from "./FundDelegator";
import { FundManagerContract } from "./FundManager";
import { RariDelegatorContract } from "./RariDelegator";
import { MockFundControllerContract } from "./MockFundController";
import { MockFundManagerContract } from "./MockFundManager";
import { SemicenContract } from "./Semicen";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "FundController"): FundControllerContract;
      require(name: "FundDelegator"): FundDelegatorContract;
      require(name: "FundManager"): FundManagerContract;
      require(name: "RariDelegator"): RariDelegatorContract;
      require(name: "MockFundController"): MockFundControllerContract;
      require(name: "MockFundManager"): MockFundManagerContract;
      require(name: "Semicen"): SemicenContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  FundControllerContract,
  FundControllerInstance,
} from "./FundController";
export { FundDelegatorContract, FundDelegatorInstance } from "./FundDelegator";
export { FundManagerContract, FundManagerInstance } from "./FundManager";
export { RariDelegatorContract, RariDelegatorInstance } from "./RariDelegator";
export {
  MockFundControllerContract,
  MockFundControllerInstance,
} from "./MockFundController";
export {
  MockFundManagerContract,
  MockFundManagerInstance,
} from "./MockFundManager";
export { SemicenContract, SemicenInstance } from "./Semicen";
