/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { IFundManagerContract } from "./IFundManager";
import { MockFundControllerContract } from "./MockFundController";
import { MockFundManagerContract } from "./MockFundManager";
import { SemicenContract } from "./Semicen";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "IFundManager"): IFundManagerContract;
      require(name: "MockFundController"): MockFundControllerContract;
      require(name: "MockFundManager"): MockFundManagerContract;
      require(name: "Semicen"): SemicenContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export { IFundManagerContract, IFundManagerInstance } from "./IFundManager";
export {
  MockFundControllerContract,
  MockFundControllerInstance,
} from "./MockFundController";
export {
  MockFundManagerContract,
  MockFundManagerInstance,
} from "./MockFundManager";
export { SemicenContract, SemicenInstance } from "./Semicen";
